### ISSUE TITLE
snoopy-enable does not support multilib architectures

### ISSUE THREAD

**Issue by bcg62** [a2o/snoopy#96] opened 2015-09-08 21:40 UTC
I've been building my own rpms and like to use snoopy for system wide logging which means I need 32/64 bit packages installed to capture both architectures.

Problem is each package tries to install its own version of snoopy-enable which only works for its respective build. It also creates transaction conflicts when attempting to install the second rpm.

**Comment by bostjan** [comment] 2015-09-09 07:51
Hi Brendan,

so I believe you are using /usr/local/$LIB/libsnoopy.so variant of enabling Snoopy in /etc/ld.so.preload?

Snoopy-enable:
I suppose I could fix it so that $LIB variation gets checked for existance. But I think it would be better to create snoopy-enable-multilib, it would lead to less convoluted code. Fortunately I do not have to deal with multilib systems, therefore I have very little incentive for looking into this, but patches are welcome.

Another thing:
Are you using RPM source from contrib/ dir? That is included in snoopy distribution as convenience and starting point for building own distro-specific packages, but it is not actively supported. See where patches for that subdir came from, and ask corresponding authors for help.

Transaction conflicts:
I underestand the problem, patches welcome. Probably one of snoopys will need to be build with some sort of executable suffix, but maybe this enabling can be moved into your package's postinstall script and ignore snoopy-enable altogether.

b.

**Comment by tkimball83** [comment] 2015-09-09 14:15
I actively maintain my snoopy spec file, which can be found here:

https://github.com/tkimball83/rpmbuild/blob/master/SPECS/snoopy.spec

I'd actually like to submit this to EPEL at some point.

**Comment by bostjan** [comment] 2015-09-09 14:45
Thanks for chipping in.

**Comment by bostjan** [comment] 2015-09-09 14:46
Brendan, If you try @tkimball83 spec, please report your success back here, if possible.

**Comment by bcg62** [comment] 2015-09-09 18:15
@bostjan yes I am using $LIB.  I have a vagrant build setup using the spec files in the project. Let me give @tkimball83 a try and see how it goes. Thanks a lot for sharing.

**Comment by bcg62** [comment] 2015-09-09 20:01
@tkimball83 used your spec file to build x86_64/i686 packages and theres still overlap between the two making it difficult to run multilib

```
Transaction Check Error:
  file /etc/ld.so.preload conflicts between attempted installs of snoopy-20150824git51914ec-1.el6.i686 and snoopy-20150824git51914ec-1.el6.x86_64
  file /usr/sbin/snoopy-disable conflicts between attempted installs of snoopy-20150824git51914ec-1.el6.i686 and snoopy-20150824git51914ec-1.el6.x86_64
  file /usr/sbin/snoopy-enable conflicts between attempted installs of snoopy-20150824git51914ec-1.el6.i686 and snoopy-20150824git51914ec-1.el6.x86_64
  file /usr/share/doc/snoopy-20150824git51914ec/doc/Makefile conflicts between attempted installs of snoopy-20150824git51914ec-1.el6.i686 and snoopy-20150824git51914ec-1.el6.x86_64
  file /usr/share/doc/snoopy-20150824git51914ec/doc/internals/Makefile conflicts between attempted installs of snoopy-20150824git51914ec-1.el6.i686 and snoopy-20150824git51914ec-1.el6.x86_64
```

**Comment by tkimball83** [comment] 2015-09-09 20:18
Are you saying the 64bit version of the package won't log 32bit applications?  I haven't tested that myself, but I think it should collect both?

@bostjan - does a 64bit version of snoopy not log 32bit applications?

**Comment by bcg62** [comment] 2015-09-09 20:24
Thats what the documentation implies

```
4.3 For multilib systems

Content of /etc/ld.so.preload should include the following line:

/usr/local/$LIB/libsnoopy.so
This applies only when you have installed both 32bit and 64bit version of the library in the appropriate paths.
```

**Comment by tkimball83** [comment] 2015-09-09 20:29
Ok, got it.  Let me see what I can do about this in the spec file.  We may need to move the location of snoopy-enable to an architecture based directory.  We will also have to manually populate /etc/ld.so.preload, as we can't have two rams writing to the same location :(

**Comment by tkimball83** [comment] 2015-09-09 21:02
Try out this commit:

https://github.com/tkimball83/rpmbuild/commit/583bd657dc2bc10c25fcc846f1ea1febcfa66637

**Comment by bcg62** [comment] 2015-09-09 21:56
looks much better, I was able to install both without issue. Thanks!

**Comment by bcg62** [comment] 2015-09-10 13:56
here's the vagrant setup i'm using to build rpms

https://github.com/bcg62/snoopy-rpm

There's a compilation error when building on el5:

```
==> snoopy-rpm: Making all in datasource
==> snoopy-rpm: make[3]: Entering directory `/usr/src/redhat/BUILD/snoopy-51914ec15ec2c6881f52e2a7df94afdf95e3b8c9/src/datasource'
==> snoopy-rpm:   CC     cmdline.lo
==> snoopy-rpm: cc1: warnings being treated as errors
==> snoopy-rpm: cmdline.c: In function 'snoopy_datasource_cmdline':
==> snoopy-rpm: cmdline.c:57: warning: unused parameter 'arg'
==> snoopy-rpm: make[3]:
==> snoopy-rpm: *** [cmdline.lo] Error 1
==> snoopy-rpm: make[3]: Leaving directory `/usr/src/redhat/BUILD/snoopy-51914ec15ec2c6881f52e2a7df94afdf95e3b8c9/src/datasource'
==> snoopy-rpm: make[2]:
==> snoopy-rpm: *** [all-recursive] Error 1
==> snoopy-rpm: make[2]: Leaving directory `/usr/src/redhat/BUILD/snoopy-51914ec15ec2c6881f52e2a7df94afdf95e3b8c9/src'
==> snoopy-rpm: make[1]:
==> snoopy-rpm: *** [all-recursive] Error 1
==> snoopy-rpm: make[1]: Leaving directory `/usr/src/redhat/BUILD/snoopy-51914ec15ec2c6881f52e2a7df94afdf95e3b8c9'
==> snoopy-rpm: make:
==> snoopy-rpm: *** [all] Error 2
==> snoopy-rpm: error:
==> snoopy-rpm: Bad exit status from /var/tmp/rpm-tmp.44222 (%build)
```

Is this something that has been seen before?

**Comment by tkimball83** [comment] 2015-09-10 16:58
This is due to -Werror being set in build/Makefile.am.common.

I updated my spec to fix this for el5 systems, try https://github.com/tkimball83/rpmbuild/commit/88ebf69d88989c12dc1cf1f9e846f33579c0e1a8

**Comment by bcg62** [comment] 2015-09-10 18:41
Updated and its still exists in build/Makefile.am.common

```
[vagrant@snoopy-rpm SPECS]$ grep Werror -B 2 snoopy.spec
%if 0%{?el6} || 0%{?el5}
%{__sed} -i -e "s/m4_esyscmd_s.*/[%{git_commit}],/" configure.ac
%{__sed} -i -e "s/\ -Werror//g" configure.ac build/Makefile.am.common

[vagrant@snoopy-rpm SPECS]$ grep Werror ../BUILD/snoopy-51914ec15ec2c6881f52e2a7df94afdf95e3b8c9/build/Makefile.am.common
AM_CFLAGS = -Wall -Werror -Wextra -Wno-unused-parameter -std=c99 -pedantic -I$(top_srcdir)
```

**Comment by tkimball83** [comment] 2015-09-10 18:43
Can you paste a snippet from your rpmbuild output?

**Comment by bcg62** [comment] 2015-09-10 18:55
https://gist.github.com/bcg62/9c703ac22589c7590f84

https://gist.github.com/bcg62/5cf2a9b8ae4ed57189f1

**Comment by tkimball83** [comment] 2015-09-10 19:05
It seems "%el5 1" is missing from /etc/rpm/macros.dist.  Can you confirm and also paste the contents of that file?  I may need to match against a different macro to support el5.

Thanks!

**Comment by bcg62** [comment] 2015-09-10 19:37
https://github.com/rerun/rerun/issues/171

/etc/rpm/macros.dist doesn't exist on el5, but installing buildsys-macros fixes it and i was able to complete the rpm build

Not sure if thats a good approach as then buildsys-macros is a requirement for using the spec on el5.

**Comment by bostjan** [comment] 2015-09-10 19:46
@tkimball83 
> This is due to -Werror being set in build/Makefile.am.common.

This does not happen on CentOS 6, right?

This is a bit of a catch-22 situation:
- on one hand -Werror takes care of many errors that might otherwise crash Snoopy and consequentially the program that is trying to do the exec
- on the other hand, using common function prototype for datasources is the only way to do it.

That said, in build/Makefile.am.common there is this setting:
AM_CFLAGS = -Wall -Werror -Wextra -Wno-unused-parameter -std=c99 -pedantic -I$(top_srcdir)

Note the -Wno-unused-parameter, which was required to circumvent the very error you two are seeing. Without it, I could not build Snoopy on any OS.

Are you saying that -Wno-unused-parameter is not doing what is is supposed to be doing on el5? I just tried building it on CentOS 5 and it works without modification you are mentioning (there are other issues with older build toolchain though).

b.

**Comment by bcg62** [comment] 2015-09-10 20:09
here is the full el5 rpm build output if it helps.

https://gist.github.com/bcg62/bd4bbb0710a18521ca04

**Comment by bostjan** [comment] 2015-09-10 20:18
@bcg62 is this build output for me or for Taylor? :)

If for me, this one is successful, right? I can not find the error mentioned about, but it is occuring as warning.

Can you reproduce the error, and please use make V=1 to produce full commands? Tnx.

**Comment by tkimball83** [comment] 2015-09-10 20:27
@bostjan - Yes, it happens on CentOS 6 and bails out, hence the removal.

**Comment by bostjan** [comment] 2015-09-11 11:44
Can not agree with you here, just tested in on centos 6 lxc:
- building from package works as expected
- building from git has flaws as toolchain is obsolete (I really dislike RH/CentOS for this reason!):

The only change needed for building from git is this:
```diff
--- a/configure.ac
+++ b/configure.ac
@@ -9,7 +9,7 @@
 AC_PREREQ([2.63])
 AC_INIT(
     [Snoopy Logger],
-    m4_esyscmd_s(echo $(./build/get-version.sh)),
+    [2.4.4],
     [https://github.com/a2o/snoopy/issues/],
     [snoopy],
     [https://github.com/a2o/snoopy/])
```

I guess the rpmbuild process is doing something funky with CC commands (adding -Werror and not -Wno-unused-parameter or sth).

b.

**Comment by bcg62** [comment] 2015-09-11 14:56
centos6, commented out %{__sed} -i -e "s/\ -Werror//g" configure.ac build/Makefile.am.common from the spec file and set V=1 for make.

https://gist.github.com/bcg62/cb03bd8fe7d01e34d750

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -Wall -Werror -Wextra -Wno-unused-parameter -std=c99 -pedantic -I../.. -I../../src -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -MT rpname.lo -MD -MP -MF .deps/rpname.Tpo -c rpname.c  -fPIC -DPIC -o .libs/rpname.o
cc1: warnings being treated as errors
rpname.c: In function 'read_proc_property':
rpname.c:131: error: 'savePtr' may be used uninitialized in this function
make[3]: *** [rpname.lo] Error 1
make[3]: Leaving directory `/root/rpmbuild/BUILD/snoopy-51914ec15ec2c6881f52e2a7df94afdf95e3b8c9/src/datasource'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/snoopy-51914ec15ec2c6881f52e2a7df94afdf95e3b8c9/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/snoopy-51914ec15ec2c6881f52e2a7df94afdf95e3b8c9'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.tJN86U (%build)
```

**Comment by bostjan** [comment] 2015-09-11 15:16
This is fixed in 2.4.4, commit b788583fb37e9ef595699e0873e791c24fa3da7d.

Please test with latest version before reporting any outstanding issues.

b.

**Comment by bcg62** [comment] 2015-09-11 15:33
@bostjan thanks, the spec was building from an older commit. 2.4.4 does indeed resolve the issue.

@tkimball83 can you update to 4541b9f328231468043ac4115099b0bc80165487 ? and remove the sed for -Werror.

Thanks!

**Comment by tkimball83** [comment] 2015-09-11 17:18
I updated to commit https://github.com/a2o/snoopy/commit/be2df693a920b23ba1ce29e9a3e8f8a41aa38e4e (one commit newer)

Spec: https://github.com/tkimball83/rpmbuild/commit/230eb063dac75b567439606d89de3a61af16d2d1

**Closed** 2015-09-16 10:01 UTC
Labels: support

**Comment by stdweird** [comment] 2015-11-15 17:51
@tkimball83 thanks for the specs!
