### ISSUE TITLE
long message_format cut off

### ISSUE THREAD

**Issue by r-lindner** [a2o/snoopy#144] opened 2019-03-19 09:35 UTC
Hello,
the ini parser only allows 200 characters on one line. I changed the message_format and the "cmd=..." is simply cut off [1]. If I insert something before "filename" [2], snoopy throws an error:
`ERROR: Closing data source tag not found: '}'` because the line is cut off in the middle of the variable.

1. `message_format = login="%{login}" ssh="%{env:SSH_CONNECTION}" sid=%{sid} tty="%{tty}" (%{tty_uid}/%{tty_username}) uid="%{username}(%{uid})/%{eusername}(%{euid})" cwd="%{cwd}" filename="%{filename}" cmd="%{cmdline}"`

1. `message_format = login="%{login}" ssh="%{env:SSH_CONNECTION}" sid=%{sid} tty="%{tty}" (%{tty_uid}/%{tty_username}) uid="%{username}(%{uid})/%{eusername}(%{euid})" cwd="%{cwd}" abc="defg" filename="%{filename}" cmd="%{cmdline}"`

https://github.com/a2o/snoopy/blob/360bb18e16ceaca16a22b94be9e17fd5f2184c01/lib/inih/src/ini.h#L105

**Comment by bostjan** [comment] 2020-10-04 12:23
Hey @r-lindner, this is a duplicate of #125. The fix was just released in the version 2.4.7.

**Closed by bostjan** 2020-10-04 12:23 UTC
