### ISSUE TITLE
source.a2o.si is unreachable

### ISSUE THREAD

**Issue by Lexx99** [a2o/snoopy#158] opened 2020-05-22 10:54 UTC
## Checklist before I submit this issue report

I confirm that:
- [x ] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [ x] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [ x] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [ x] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

source.a2o.si is unreachable - so I'm unable to download the snoopy-2.4.6.tar.gz tarball.

**Comment by bostjan** [comment] 2020-10-03 23:37
Fixed, this is duplicate of #146

**Closed by bostjan** 2020-10-03 23:37 UTC
