### ISSUE TITLE
FTBFS with GCC-9

### ISSUE THREAD

**Issue by MarcosFouces** [a2o/snoopy#148] opened 2019-09-08 17:39 UTC
Hello
Snoopy fails to build in a test rebuild on at least amd64 with gcc-9/g++-9, but succeeds to build with gcc-8/g++-8. 

The full build log can be found at:
http://people.debian.org/~doko/logs/gcc9-20190321/snoopy_2.4.6-5_unstable_gcc9.log
The last lines of the build log are at the end of this report.

The next release of Debian (Bullseye) cannot include Snoopy if this issue is not solved.

Greetings.

**Comment by rhash** [comment] 2019-10-27 16:25
@MarcosFouces, this bug is duplicate of #142, the fix is PR #143.

Current master 360bb18e16ceaca16a22b94be9e17fd5f2184c01 is sucesfully compiled by gcc 9.2.1.

**Comment by samueloph** [comment] 2019-10-27 18:35
@rhash are there plans of making a new release soon? I see that the last one is from 2016, making a new release would be a good way of showing that there are important fixes made since then.

Thanks,

**Comment by rhash** [comment] 2019-10-27 22:54
@samueloph No idea.
I've just came here from https://bugs.debian.org/925833 to investigate the bug root cause ;)

**Comment by samueloph** [comment] 2019-10-28 00:46
@rhash sorry, I got confused and thought you were the upstream, hahaha

@bostjan do you have plans for a new release?

**Comment by bostjan** [comment] 2020-10-04 03:23
Thanks @rhash for jumping in.

@samueloph:
Fix released in https://github.com/a2o/snoopy/releases/tag/snoopy-2.4.7.

**Closed by bostjan** 2020-10-04 03:23 UTC
Labels: Component: Core Library, Resolution: Duplicate, Type: Bug
