### ISSUE TITLE
Errors building on el8

### ISSUE THREAD

**Issue by bcg62** [a2o/snoopy#154] opened 2019-12-03 19:55 UTC
## Checklist before I submit this issue report

I confirm that:
- [x ] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [ x] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [x ] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [x ] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | |
| Linux distribution:                 | centos            | |
| Distribution version:               | el8            | |
| Snoopy version:                     | 2.4.6            | |
| Snoopy config file was used:        | yes   | |
| Snoopy threading support enabled:   | yes   | |

## Issue description - How was Snoopy installed
 
RPM build: https://github.com/linuxhq/rpmbuild-snoopy/blob/master/SPECS/snoopy.spec
```
%prep
%setup -q -n %{name}-%{name}-%{version}
autoreconf -i -v
%build
%configure --enable-everything
%{__make} %{?_smp_mflags}

%install
%{__make} install DESTDIR=%{buildroot}
echo '%{_prefix}/$LIB/lib%{name}.so' >> %{buildroot}%{_sysconfdir}/ld.so.preload
for i in enable disable;
do
  %{__mv} -f %{buildroot}%{_sbindir}/%{name}-${i} \
             %{buildroot}%{_sbindir}/%{name}-${i}.%{_arch}
done
```

## Issue description - Describe the problem you are having

```
/usr/bin/make  all-recursive
make[1]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6'
Making all in etc
make[2]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/etc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/etc'
Making all in lib
make[2]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib'
Making all in inih
make[3]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib/inih'
Making all in src
make[4]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib/inih/src'
  CC       ini.lo
  CCLD     libinih.la
make[4]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib/inih/src'
make[4]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib/inih'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib/inih'
make[3]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib/inih'
make[3]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib'
make[2]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/lib'
Making all in src
make[2]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/src'
Making all in eventsource
make[3]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/src/eventsource'
  CC       libsnoopy_eventsource_execve_wrapper_la-execve_wrapper.lo
  CCLD     libsnoopy_eventsource_execve_wrapper.la
make[3]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/src/eventsource'
Making all in datasource
make[3]: Entering directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/src/datasource'
  CC       cmdline.lo
  CC       cwd.lo
  CC       datetime.lo
  CC       noop.lo
  CC       domain.lo
  CC       egid.lo
cmdline.c: In function 'snoopy_datasource_cmdline':
cmdline.c:71:79: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
     for (cmdLineArgCount=0 ; *(snoopy_inputdatastorage->argv+cmdLineArgCount) != '\0' ; cmdLineArgCount++);
                                                                               ^~
cmdline.c:71:30: note: did you mean to dereference the pointer?
     for (cmdLineArgCount=0 ; *(snoopy_inputdatastorage->argv+cmdLineArgCount) != '\0' ; cmdLineArgCount++);
                              ^
  CC       egroup.lo
cc1: all warnings being treated as errors
make[3]: *** [Makefile:815: cmdline.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC       env.lo
make[3]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/src/datasource'
make[2]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6/src'
make[2]: *** [Makefile:840: all-recursive] Error 1
make[1]: *** [Makefile:509: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/snoopy-snoopy-2.4.6'
```

## Steps to reproduce

compile 2.4.6 on el8

## Expected result

success

## Actual result

failure shown above

**Comment by bostjan** [comment] 2020-10-04 12:21
Hey @bcg62, this is a duplicate of #122. Fixed in 2.4.7.

**Closed by bostjan** 2020-10-04 12:21 UTC
