### ISSUE TITLE
CoreOS or Docker support

### ISSUE THREAD

**Issue by mrsanuk** [a2o/snoopy#138] opened 2018-07-18 09:31 UTC
Have you ever tried run snoopy on CoreOS or in Docker container?

**Comment by dAnjou** [comment] 2020-10-02 09:55
@rdlmda, this is most likely caused by #158. A workaround is to install from a Git ref: https://github.com/a2o/snoopy/blob/360bb18e16ceaca16a22b94be9e17fd5f2184c01/doc/install/bin/snoopy-install.sh#L29 which just worked for me.

**Comment by bostjan** [comment] 2020-10-04 01:12
Most likely a duplicate of #146, just as @dAnjou suggested. Closing now, do reopen it if the issue still persists.

**Closed by bostjan** 2020-10-04 01:12 UTC
Labels: Component: Installation, Resolution: Incomplete Report, Type: Support Request
