### ISSUE TITLE
console getting flooded with snoopy-2.2.3

### ISSUE THREAD

**Issue by henkjan** [a2o/snoopy#30] opened 2015-02-19 10:58 UTC
Installed the latest snoopy release with snoopy-install.sh on Redhat 6.6

After enabling the console is flooded with snoopy logging. Writing the messages to syslog seems broken in this release.

Tried to configure /etc/snoopy.ini

`output = syslog`

made no difference

**Comment by rupikakapoor** [comment] 2015-02-19 17:12
I am facing same issue, I tried to configure ../etc/snoopy.ini 

syslog_facility = LOG_AUTHPRIV
syslog_level = LOG_DEBUG

as well as "./configure -enable-config-file --with-syslog-facility=AUTHPRIV --with-syslog-level=DEBUG —enable-root-only"

but no difference.

**Comment by renier** [comment] 2015-02-21 13:31
+1 I'm also experiencing this

**Comment by bostjan** [comment] 2015-02-22 11:31
Are you guys using stock rsyslog from rh packages or something else?

B.

**Comment by bostjan** [comment] 2015-02-22 16:14
Fixed in 2.2.4.

It turns out "devlog" output provider was implemented too-hastily and did not set syslog priority and facility correctly. Therefore all messages were treated with EMERG priority, which on RH gets sent to console by default.

About "output = syslog":
This is fixed now, but this variable was actually pending implementation and had a bit TODO next to it in snoopy.ini :)


b.

**Comment by tkimball83** [comment] 2015-02-28 01:09
So while this is mostly fixed, I noticed it come back when I did an ansible run on one of my dev hosts:

TASK: [terminus | command | pwck] *********************************************

Message from syslogd@xxx at Feb 27 17:04:51 ...
 ecos: tkimball uid:0 sid:1375 tty:(none) cwd:/etc/ansible filename:/usr/local/bin/pwck]: pwck -s

Message from syslogd@xxx at Feb 27 17:04:51 ...
 ecos:tkimball uid:0 sid:1375 tty:(none) cwd:/etc/ansible filename:/sbin/pwck]: pwck -s

Message from syslogd@xxx at Feb 27 17:04:51 ...
 ecos:tkimball uid:0 sid:1375 tty:(none) cwd:/etc/ansible filename:/bin/pwck]: pwck -s

Message from syslogd@xxx at Feb 27 17:04:51 ...
 ecos:tkimball uid:0 sid:1375 tty:(none) cwd:/etc/ansible filename:/usr/sbin/pwck]: pwck -s

Note that the beginning of the line is supposed to say 'gecos', not 'ecos'.

Let me know if I can assist by providing more information.

Thanks!

**Comment by bostjan** [comment] 2015-03-02 09:01
It seems like old library is still loaded somewhere - did you reboot the system after snoopy upgrade?

B.

**Comment by tkimball83** [comment] 2015-03-02 23:53
Yup, rebooted.  If you do the following, you should be able to reproduce it.  You'll need the EPEL repository installed.

$ yum -y install ansible
$ ansible -m setup localhost

Message from syslogd@xxx at Mar  2 15:50:51 ...
 ecos:tkimball83 uid:0 sid:1154 tty:/dev/pts/1 cwd:/root filename:/usr/local/bin/ssh]: ssh -o ControlPersist

Message from syslogd@xxx at Mar  2 15:50:51 ...
 ecos:tkimball83 uid:0 sid:1154 tty:/dev/pts/1 cwd:/root filename:/sbin/ssh]: ssh -o ControlPersist

Message from syslogd@xxx at Mar  2 15:50:51 ...
 ecos:tkimball83 uid:0 sid:1154 tty:/dev/pts/1 cwd:/root filename:/bin/ssh]: ssh -o ControlPersist

Message from syslogd@xxx at Mar  2 15:50:51 ...
 ecos:tkimball83 uid:0 sid:1154 tty:/dev/pts/1 cwd:/root filename:/usr/sbin/ssh]: ssh -o ControlPersist

Message from syslogd@xxx at Mar  2 15:50:51 ...
 ecos:tkimball83 uid:0 sid:1154 tty:/dev/pts/1 cwd:/root filename:/usr/bin/ssh]: ssh -o ControlPersist

**Comment by bostjan** [comment] 2015-03-03 22:34
Yes, I see it now.

For some reason that is unknown ATM some messages get through without proper prefix that defines snoopy ID and log priority/facility.

Will look into this.
b.

**Comment by bostjan** [comment] 2015-03-03 23:17
Found it, I think it is fixed now (devlog output provider was not resetting configuration after changing it to use another output provider as a subroutine).

Could you try git master and confirm that this fixes it for you? Tnx.

**Comment by tkimball83** [comment] 2015-03-03 23:39
Looks good now! :)

**Comment by bostjan** [comment] 2015-03-04 22:36
Fix released in 2.2.5 (will be up any minute now).

**Closed by bostjan** 2015-03-04 22:36 UTC
