### ISSUE TITLE
Snoopy (2.4.6) and monit (5.14) don't play nicely.

### ISSUE THREAD

**Issue by tkimball83** [a2o/snoopy#116] opened 2017-02-26 19:49 UTC
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [x] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [x] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [x] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | x86 is not supported anymore     |
| Linux distribution:                 | CentOS            | |
| Distribution version:               | 7.               | |
| Snoopy version:                     | 2.4.6            | |
| Snoopy config file was used:        | yes   | snoopy-install.sh enables this by default |
| Snoopy threading support enabled:   | yes   | not enabled by default as of v2.4.4       |

## Issue description - How was Snoopy installed

Custom built rpm, spec file below.

https://github.com/linuxhq/rpmbuild-snoopy/blob/master/SPECS/snoopy.spec

## Issue description - Describe the problem you are having

I recently installed monit to monitor permissions and ownership on some files and noticed when snoopy is enabled that monit fails to execute commands.  Note that monit uses execv().

## Expected results

Permissions on /bin/su should be changed back to root:root/0755

## Actual result

No change

## Steps to reproduce

Install snoopy and monit:

`curl -s https://packagecloud.io/install/repositories/linuxhq/snoopy/script.rpm.sh | sudo bash`
`sudo yum install snoopy-2.4.6-1.el7.centos.x86_64`
`yum -y install monit`

Apply the following config:

/etc/monit.d/snoopy:

`check file su with path /bin/su`
`  if failed gid 0 then exec "/bin/bash -c '/bin/chown 0:0 /bin/su'"`
`  if failed uid 0 then exec "/bin/bash -c '/bin/chown 0:0 /bin/su'"`
`  if failed permission 755 then exec "/bin/bash -c '/bin/chmod 755 /bin/su'"`

Change permissions of /bin/su to 000 nobody:nobody

`chmod 000 /bin/su`
`chown nobody: /bin/su`

Re-login and start monit:

`systemctl start monit`

Watch the logs.  Monit will detect that permissions are incorrect but when attempting to execute the command to fix it nothing happens.  Example log:

[PST Feb 26 11:43:32] error    : 'su' permission test failed for /bin/su [current permission 0000]
[PST Feb 26 11:43:32] info     : 'su' exec: /bin/bash
[PST Feb 26 11:43:32] error    : 'su' uid test failed for su -- current uid is 99
[PST Feb 26 11:43:32] info     : 'su' exec: /bin/bash
[PST Feb 26 11:43:32] error    : 'su' gid test failed for su -- current gid is 99
[PST Feb 26 11:43:32] info     : 'su' exec: /bin/bash

$ ls -al /bin/su
---------- 1 nobody nobody 32088 Nov  5 15:27 /bin/su

Disabling snoopy, re-logging in, and restarting monit fixes the issue.

This may be the place to start looking, but I'm just guessing...

`11:44:46 [tkimball:~/monit] master ± grep execv spawn.c`
`(void) execv(C->arg[0], C->arg);`

**Comment by tkimball83** [comment] 2017-03-08 05:03
I didn't catch this in the logs before, but this is actually causing monit to segfault.

kernel: monit[27230]: segfault at 12 ip 00000000004495fc sp 00007ffc5b278ad0 error 4 in monit[400000+92000]
kernel: monit[27232]: segfault at 12 ip 00000000004495fc sp 00007ffc5b278ce0 error 4 in monit[400000+92000]
monit[27269]: segfault at 12 ip 00000000004495fc sp 00007ffc5b278ad0 error 4 in monit[400000+92000]
monit[27271]: segfault at 12 ip 00000000004495fc sp 00007ffc5b278ce0 error 4 in monit[400000+92000]

**Comment by bcg62** [comment] 2017-04-22 13:12
I am also seeing this same issue

**Comment by bostjan** [comment] 2017-07-28 10:36
@tkimball83 @bcg62 does building Snoopy with `--enable-thread-safety` resolve your issues?

**Comment by tkimball83** [comment] 2017-07-31 01:13
My build includes --enable-everything

https://github.com/linuxhq/rpmbuild-snoopy/blob/master/SPECS/snoopy.spec

**Comment by bostjan** [comment] 2018-04-15 00:13
I've replicated this locally - monit does double fork to execute external command and the second child segfaults somewhere in the `snoopy_log_syscall_execv(filename, argv)` function, here:
https://github.com/a2o/snoopy/blob/master/src/eventsource/execve_wrapper.c#L61

@tkimball83, did you get any core file generated out of this?

**Comment by bostjan** [comment] 2018-04-15 00:25
`./configure --enable-everything --disable-thread-safety` "resolves" the issue.

**Comment by bostjan** [comment] 2018-04-15 01:24
Currently I have no idea yet what is going on. It might be related to `monit`'s usage of `vfork` which causes the child process to be executed in parent context. It might be that mutex does not work as expected in such context.

**Comment by bostjan** [comment] 2018-04-15 01:29
For the reference, this is how to reproduce the issue:

    lxc-create -n t-centos7-snoopy-bug116 -t download -- -d centos -r 7 -a amd64
    lxc-start   -n t-centos7-snoopy-bug116
    lxc-attach -n t-centos7-snoopy-bug116

Inside container:

    1. Enable epel repo
    2. Follow this issue's "Steps to reproduce" section.
    3. Start the monit with `/usr/bin/monit -I -vv` or prefix it with `strace -tt -f -s64 ...` to observe its operation.

**Comment by bostjan** [comment] 2020-11-26 16:37
I've just retested this as described above, with both the reported 2.4.6 and with the latest 2.4.9 version, both **installed from source**, and it looks like it's working fine:
```
Nov 26 16:27:07 t-centos7-snoopy-bug116 snoopy[462]: [uid:0 sid:342 tty:(none) cwd:/ filename:/usr/bin/systemctl]: systemctl start monit
Nov 26 16:27:07 t-centos7-snoopy-bug116 snoopy[463]: [uid:0 sid:342 tty:(none) cwd:/ filename:/usr/bin/systemd-tty-ask-password-agent]: /usr/bin/systemd-tty-ask-password-agent --watch
Nov 26 16:27:07 t-centos7-snoopy-bug116 snoopy[464]: [uid:0 sid:342 tty:(none) cwd:/ filename:/usr/bin/pkttyagent]: /usr/bin/pkttyagent --notify-fd 5 --fallback
Nov 26 16:27:07 t-centos7-snoopy-bug116 snoopy[465]: [uid:0 sid:465 tty:(none) cwd:/ filename:/usr/bin/monit]: /usr/bin/monit -I
Nov 26 16:27:07 t-centos7-snoopy-bug116 snoopy[472]: [uid:0 sid:471 tty:(none) cwd:/ filename:/bin/bash]: /bin/bash -c /bin/chmod 4755 /bin/su
Nov 26 16:27:07 t-centos7-snoopy-bug116 snoopy[472]: [uid:0 sid:471 tty:(none) cwd:/ filename:/bin/chmod]: /bin/chmod 4755 /bin/su
Nov 26 16:27:10 t-centos7-snoopy-bug116 snoopy[474]: [uid:0 sid:342 tty:(none) cwd:/ filename:/usr/bin/tail]: tail -f /var/log/secure
```

At this point, it looks like this was an issue with how the RPM package was created. Since I can't reproduce this with a stock Snoopy, I'll close this bug report. If it still doesn't work for you (with stock Snoopy, not with a RPM), let me know (and provide a Docker-based method of reproduction that I can use to diagnose the issue). If RPM is the cause of the issue, then talk to the RPM package maintainer.

**Closed by bostjan** 2020-11-26 16:37 UTC
Labels: Component: Core Library, Type: Bug
